### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip-python-extensions#4]
trying to use Python 3 (amd64 on Win7 64-bit) I get 
![2015-07-23 11_09_56-preferences](https://cloud.githubusercontent.com/assets/8655419/8847131/3e3156aa-312c-11e5-8232-506f9e102bab.png)

Not sure where the python_message.py is or if that is a bug by protobuf itself.

**Comment by dietzc** [comment]
python 3 is not supported by the KNIME Python Extension, yet.
